function(qasr_configure_blas target_name)
    if(APPLE)
        find_library(QASR_ACCELERATE_FRAMEWORK Accelerate REQUIRED)
        target_compile_definitions(${target_name} PUBLIC QASR_BLAS_ACCELERATE=1)
        target_link_libraries(${target_name} PUBLIC ${QASR_ACCELERATE_FRAMEWORK})
        return()
    endif()

    find_package(OpenBLAS REQUIRED)
    target_compile_definitions(${target_name} PUBLIC QASR_BLAS_OPENBLAS=1)

    if(TARGET OpenBLAS::OpenBLAS)
        target_link_libraries(${target_name} PUBLIC OpenBLAS::OpenBLAS)
        return()
    endif()

    if(DEFINED OpenBLAS_INCLUDE_DIRS)
        target_include_directories(${target_name} PUBLIC ${OpenBLAS_INCLUDE_DIRS})
    elseif(DEFINED OpenBLAS_INCLUDE_DIR)
        target_include_directories(${target_name} PUBLIC ${OpenBLAS_INCLUDE_DIR})
    endif()

    if(DEFINED OpenBLAS_LIBRARIES)
        target_link_libraries(${target_name} PUBLIC ${OpenBLAS_LIBRARIES})
    elseif(DEFINED OpenBLAS_LIBRARY)
        target_link_libraries(${target_name} PUBLIC ${OpenBLAS_LIBRARY})
    else()
        message(FATAL_ERROR "OpenBLAS found, but no link target or library path was exported.")
    endif()
endfunction()
